version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skinport
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
#    volumes:
#      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  skinport-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_USER: postgres
      DB_HOST: postgres
      DB_NAME: skinport
      DB_PASSWORD: postgres
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVER_PORT: 3000
      SKINPORT_URL: https://api.skinport.com/v1
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

#volumes:
#  postgres-data: